version: '3'

services:
  api:
    container_name: backend-compasso-uol
    build: '.'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules      
    ports:
      - '8000:8000'
    links:
      - mongo
  mongo:
    container_name: backend-compasso-uol-database
    image: mongo:3.6
    ports:
      - '27017:27017'

